#!/usr/bin/env python3
"""Aggregate the asymmetric-capacity sweep into the §5.2 Tab 3 (d)
asymmetric block.

Reads metrics.json files from exp3 sweep (4 scenarios × 5 protocols ×
20 seeds = 400 runs), extracts delivery%, p99 ms, and 95% CI per
(scenario, policy), emits a LaTeX fragment that drops into Tab 3 as
a new "(d) Asymmetric capacity" section.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from statistics import mean, stdev

POLICIES = [
    ("conga_like",          "CONGA-like"),
    ("information_routing", "IR"),
]

SCENARIO_ORDER = [
    ("exp3_asym_a1_baseline",       r"A1 baseline ($T{=}500$ only)"),
    ("exp3_asym_a2_spine_narrowed", r"A2 spine ring @ $60$\,Mbps"),
    ("exp3_asym_a3_chord_narrowed", r"A3 chords @ $60$\,Mbps"),
    ("exp3_asym_a4_mixed",          r"A4 mixed (A2 $\cup$ A3)"),
]


def t_critical(n: int) -> float:
    table = {2: 12.706, 5: 2.776, 10: 2.262, 19: 2.093, 20: 2.086, 29: 2.045}
    if n < 2:
        return float("nan")
    for k in sorted(table.keys()):
        if n - 1 <= k:
            return table[k]
    return 1.96


def agg(values: list[float]) -> tuple[float, float]:
    if not values:
        return (float("nan"), float("nan"))
    n = len(values)
    m = mean(values)
    if n < 2:
        return (m, 0.0)
    s = stdev(values)
    return (m, t_critical(n) * s / math.sqrt(n))


def collect(run_dir: Path) -> dict[tuple[str, str], dict[str, list[float]]]:
    out: dict[tuple[str, str], dict[str, list[float]]] = {}
    for metrics_path in run_dir.rglob("metrics.json"):
        try:
            d = json.loads(metrics_path.read_text())
        except Exception:
            continue
        if d.get("returncode", -1) != 0:
            continue
        scen = d.get("scenario", "")
        proto = d.get("protocol", "")
        key = (scen, proto)
        s = d.get("summary", {})
        delivery = float(s.get("delivery_ratio", 0)) * 100.0
        p99 = float(s.get("p99_delay_ms", 0))
        slot = out.setdefault(key, {"del": [], "p99": []})
        slot["del"].append(delivery)
        slot["p99"].append(p99)
    return out


def fmt_pair(values: list[float], decimals: int = 2) -> str:
    """Format mean only (CI shown in dedicated CI column to save width)."""
    m, _ = agg(values)
    if math.isnan(m):
        return "--"
    return f"${m:.{decimals}f}$"


def emit_latex(by_key: dict[tuple[str, str], dict[str, list[float]]],
               out: Path) -> None:
    lines: list[str] = []
    lines.append(r"% Tab 3 (c) Asymmetric capacity — generated by")
    lines.append(r"% tools/aggregate_asymmetric_capacity.py from asymmetric-capacity sweep.")
    lines.append(r"\midrule")
    lines.append(r"\textit{(c) Asymmetric capacity (exp3, cascade $T{=}500$\,ms)} \\")
    for scen, label in SCENARIO_ORDER:
        cl = by_key.get((scen, "conga_like"), {"del": [], "p99": []})
        ir = by_key.get((scen, "information_routing"), {"del": [], "p99": []})
        ir_d_mean = agg(ir["del"])[0]
        cl_d_mean = agg(cl["del"])[0]
        ir_d_better = ir_d_mean > cl_d_mean
        cl_del_cell = fmt_pair(cl["del"])
        cl_p99_cell = fmt_pair(cl["p99"], 1)
        cl_ci_cell = f"${agg(cl['del'])[1]:.2f}$" if cl["del"] else "--"
        ir_del_cell = fmt_pair(ir["del"])
        ir_p99_cell = fmt_pair(ir["p99"], 1)
        ir_ci_cell = f"${agg(ir['del'])[1]:.2f}$" if ir["del"] else "--"
        if ir_d_better:
            ir_del_cell = f"\\textbf{{{ir_del_cell[1:-1]}}}".replace(
                "_{\\pm", "_{\\pm"
            )
            ir_del_cell = "$" + ir_del_cell[8:-1] + "$" if "textbf" in ir_del_cell else ir_del_cell
        line = (f"{label} & {cl_del_cell} & {cl_p99_cell} & {cl_ci_cell} "
                f"& {ir_del_cell} & {ir_p99_cell} & {ir_ci_cell} \\\\")
        lines.append(line)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[write] {out}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-dir", type=Path, required=True)
    ap.add_argument("--out-tex", type=Path, required=True)
    args = ap.parse_args()
    by_key = collect(args.run_dir)
    print(f"# exp3 asymmetric aggregate ({args.run_dir})\n")
    for scen, label in SCENARIO_ORDER:
        for proto, plabel in POLICIES:
            s = by_key.get((scen, proto), {"del": [], "p99": []})
            n = len(s["del"])
            if n == 0:
                print(f"{label:<45s} {plabel:<12s} n={n}")
                continue
            d_m, d_h = agg(s["del"])
            p_m, p_h = agg(s["p99"])
            print(f"{label:<45s} {plabel:<12s} n={n:>2d} "
                  f"del={d_m:>6.2f}±{d_h:.2f}%  "
                  f"p99={p_m:>6.1f}±{p_h:.1f}ms")
    emit_latex(by_key, args.out_tex)


if __name__ == "__main__":
    main()
