#!/usr/bin/env python3
"""Aggregate v5_exp10 trace-replay sweep into the §5.2 Tab 2 (c)
real-trace row.

3 scenarios (load 1x/2x/4x) × 5 protocols × 20 seeds. Emits one row
per (load, policy) plus the IR-CONGA delivery delta.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from statistics import mean, stdev

POLICIES_ALL = [
    ("load_aware_ecmp",     "LA-ECMP"),
    ("conga_like",          "CONGA-like"),
    ("information_routing", "IR"),
]

LOAD_ORDER = [
    ("exp10_trace_fb_hadoop_load1x", r"FB Hadoop trace, $1\times$"),
    ("exp10_trace_fb_hadoop_load2x", r"FB Hadoop trace, $2\times$"),
    ("exp10_trace_fb_hadoop_load4x", r"FB Hadoop trace, $4\times$"),
]


def t_critical(n: int) -> float:
    table = {2: 12.706, 5: 2.776, 10: 2.262, 19: 2.093, 20: 2.086}
    if n < 2:
        return float("nan")
    for k in sorted(table.keys()):
        if n - 1 <= k:
            return table[k]
    return 1.96


def agg(values: list[float]) -> tuple[float, float]:
    if not values:
        return (float("nan"), float("nan"))
    n = len(values)
    m = mean(values)
    if n < 2:
        return (m, 0.0)
    s = stdev(values)
    return (m, t_critical(n) * s / math.sqrt(n))


def collect(run_dir: Path):
    out: dict[tuple[str, str], dict[str, list[float]]] = {}
    for metrics_path in run_dir.rglob("metrics.json"):
        try:
            d = json.loads(metrics_path.read_text())
        except Exception:
            continue
        if d.get("returncode", -1) != 0:
            continue
        scen, proto = d.get("scenario", ""), d.get("protocol", "")
        s = d.get("summary", {})
        meta = d.get("metadata", {})
        delivery = float(s.get("delivery_ratio", 0)) * 100.0
        p99 = float(s.get("p99_delay_ms", 0))
        writes = float(meta.get("control_metric_writes", 0))
        slot = out.setdefault((scen, proto),
                              {"del": [], "p99": [], "writes": []})
        slot["del"].append(delivery)
        slot["p99"].append(p99)
        slot["writes"].append(writes)
    return out


def fmt_pair(values: list[float], decimals: int = 2) -> str:
    m, h = agg(values)
    if math.isnan(m):
        return "--"
    return f"${m:.{decimals}f}_{{\\pm {h:.{decimals}f}}}$"


def fmt_writes(values: list[float]) -> str:
    if not values:
        return "--"
    m = mean(values)
    if m >= 1e6:
        return f"{m/1e6:.1f}M"
    if m >= 1e3:
        return f"{m/1e3:.0f}k"
    return f"{m:.0f}"


def emit_latex(by_key, out: Path) -> None:
    lines: list[str] = []
    lines.append(r"% Tab 2 (c) Real-trace replay — generated by")
    lines.append(r"% tools/aggregate_exp10_trace.py from exp10 sweep.")
    lines.append(r"\midrule")
    lines.append(r"\textit{(c) Real-trace replay (exp10, FB-Hadoop-style synthesis)} \\")
    for scen, label in LOAD_ORDER:
        cells = []
        for proto, _ in POLICIES_ALL:
            s = by_key.get((scen, proto), {"del": [], "p99": [], "writes": []})
            cells.append(fmt_pair(s["del"]))
            cells.append(fmt_pair(s["p99"], 1))
            cells.append(fmt_writes(s["writes"]))
        # delta IR - CL
        cl = by_key.get((scen, "conga_like"), {"del": [], "p99": [], "writes": []})
        ir = by_key.get((scen, "information_routing"),
                        {"del": [], "p99": [], "writes": []})
        if cl["del"] and ir["del"]:
            delta = agg(ir["del"])[0] - agg(cl["del"])[0]
            delta_cell = f"${delta:+.2f}$"
        else:
            delta_cell = "--"
        line = f"{label} & " + " & ".join(cells) + f" & {delta_cell} \\\\"
        lines.append(line)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[write] {out}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-dir", type=Path, required=True)
    ap.add_argument("--out-tex", type=Path, required=True)
    args = ap.parse_args()
    by_key = collect(args.run_dir)
    print(f"# exp10 trace aggregate ({args.run_dir})\n")
    for scen, label in LOAD_ORDER:
        for proto, plabel in POLICIES_ALL:
            s = by_key.get((scen, proto), {"del": [], "p99": [], "writes": []})
            n = len(s["del"])
            if n == 0:
                print(f"{label:<32s} {plabel:<12s} n={n}")
                continue
            d_m, d_h = agg(s["del"])
            p_m, p_h = agg(s["p99"])
            print(f"{label:<32s} {plabel:<12s} n={n:>2d} "
                  f"del={d_m:>6.2f}±{d_h:.2f}% "
                  f"p99={p_m:>7.1f}±{p_h:.1f}ms "
                  f"writes={fmt_writes(s['writes'])}")
    emit_latex(by_key, args.out_tex)


if __name__ == "__main__":
    main()
